site_name: Shuo's Linux TCP/IP notes
theme:
  name: readthedocs
  analytics:
    gtag: G-4PL3B2ZGE8
nav:
  - Home: index.md
  - Sockets: sockets.md
  - Throughput: throughput.md
  - Profiling: profile.md
  - Walkthrough: walkthrough.md
  - Nagle's Algothrim: nagle.md
  - Slow Start: slowstart.md
  - Loss Recovery: recovery.md
  - Reno CC: reno.md
  - W. Richard Stevens: stevens.md
  - Links: links.md
  - History: history.md
extra_css: [extra.css]
markdown_extensions:
  - mkdocs_graphviz:
        light_theme: 000000
        dark_theme: FFFFFF
        color: 000000
        bgcolor: none

extra_javascript:
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js
